verbose: false
instrumentation:
    root: .
    extensions:
        - .js
    default-excludes: true
    excludes: []
    variable: __coverage__
    compact: true
    preserve-comments: false
    complete-copy: false
    save-baseline: false
    baseline-file: ./coverage/coverage-baseline.raw.json
    include-all-sources: true
    include-pid: false
    es-modules: false
    auto-wrap: true
reporting:
    print: summary
    reports:
        - lcov
    dir: ./coverage
    summarizer: pkg
    report-config: {}
    watermarks:
        statements: [50, 80]
        functions: [50, 80]
        branches: [50, 80]
        lines: [50, 80]
hooks:
    hook-run-in-context: false
    post-require-hook: null
    handle-sigint: false
check:
    global:
        statements: 80
        lines: 80
        branches: 80
        functions: 80
        excludes: []
    each:
        statements: 80
        lines: 80
        branches: 80
        functions: 80
        excludes: []