sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - "node_modules"
node_js:
  - '10'
  - '8'
  - '6'
install: yarn --frozen-lockfile --ignore-engines
before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn test
after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json
  - 'if [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then yarn semantic-release; fi'
