name: "Publish built version to build branch"

on:
  workflow_run:
    workflows: ["All tests"]
    types:
      - completed

jobs:
  publish:
    name: "Commit to build branch"
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event != 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn
      - run: yarn build
      - run: yarn prepare-publish
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Build: ({sha}) {msg}"
          branch: build
          repository: build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./package.json
          access: "public"
